### ISSUE TITLE
level3/irr error

### ISSUE THREAD

**Issue by aftabsiddiqui** [InternetHealthReport/route-origin-validator#1]
Receiving this error with level3 irr db. Most likely because of "." in the AS notation. 

Error in db/irr/level3.db.gz, invalid ASN!
{'route': '186.211.112.0/20', 'descr': 'Diveo Telecom Customer Proxy Route', 'origin': 'AS4.603', 'notify': 'jtoni@diveo.net.br', 'mnt-by': 'DIVEO-MNT', 'changed': 'jrodrigues@diveo.net.br 20110118', 'source': 'LEVEL3'}
Error in db/irr/level3.db.gz, invalid ASN!
{'route': '186.211.120.0/24', 'descr': 'Diveo Telecom Customer Proxy Route', 'origin': 'AS4.603', 'notify': 'jtoni@diveo.net.br', 'mnt-by': 'DIVEO-MNT', 'changed': 'jrodrigues@diveo.net.br 20110118', 'source': 'LEVEL3'}
Error in db/irr/level3.db.gz, invalid ASN!
{'route': '186.211.120.0/21', 'descr': 'Diveo Telecom Customer Proxy Route', 'origin': 'AS4.603', 'notify': 'jtoni@diveo.net.br', 'mnt-by': 'DIVEO-MNT', 'changed': 'jrodrigues@diveo.net.br 20110118', 'source': 'LEVEL3'}
Error in db/irr/level3.db.gz, invalid ASN!
{'route': '186.211.112.0/21', 'descr': 'Diveo Telecom Customer Proxy Route', 'origin': 'AS4.603', 'notify': 'jtoni@diveo.net.br', 'mnt-by': 'DIVEO-MNT', 'changed': 'jrodrigues@diveo.net.br 20110118', 'source': 'LEVEL3'}
Error in db/irr/level3.db.gz, invalid ASN!
{'route': '63.235.122.0/24', 'descr': 'Higher One Inc', 'origin': 'AS6.23', 'mnt-by': 'ONECOMM-MNT', 'changed': 'ewallace@onecommunications.com 20110209', 'source': 'LEVEL3'}
Error in db/irr/level3.db.gz, invalid ASN!
{'route': '63.144.247.0/24', 'descr': 'Higher One', 'origin': 'AS6.23', 'mnt-by': 'ONECOMM-MNT', 'changed': 'bcarl@onecommunications.com 20120711', 'source': 'LEVEL3'}
Loading: db/rpki/export.json
{'irr': 'NotFound', 'rpki': 'Valid'}

**Comment by romain-fontugne** [comment]
Yes, I have the same errors. I think this should be fixed in IRR.

**Comment by ritikBhandari** [comment]
Is this issue fixed?

**Comment by romain-fontugne** [comment]
Honestly I don't understand that AS notation. I think this is a typo in IRR database and in this case we cannot do anything for it. I'll close this for now but feel free to reopen if we can handle that better.
