### ISSUE TITLE
RIPE RPKI archive format changed (.xz)

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/route-origin-validator#14]
The data for the ripe archive is compressed in xv format (see https://ftp.ripe.net/rpki/apnic.tal/2023/11/06/). This change will break the code when they will stop producing the .csv files.

We should update URLS from where we get data (https://github.com/InternetHealthReport/route-origin-validator/blob/a06fb26ea629a1aee0f64b6525c7ed0bbf347824/rov/__init__.py#L66)
And uncompress files when reading these files.

**Comment by KiranSatyaRaj** [comment]
> The data for the ripe archive is compressed in xv format (see https://ftp.ripe.net/rpki/apnic.tal/2023/11/06/). This change will break the code when they will stop producing the .csv files.
> 
> We should update URLS from where we get data (
> 
> https://github.com/InternetHealthReport/route-origin-validator/blob/a06fb26ea629a1aee0f64b6525c7ed0bbf347824/rov/__init__.py#L66
> 
> )
> And uncompress files when reading these files.

Hi @romain-fontugne -
I just need some clarification, did you mean `xz` format or is it `xv` format?

**Comment by MAVRICK-1** [comment]
*It can be done by using following modules :* 
-  [lzma](https://docs.python.org/3/library/lzma.html) for **xz** Decompression
- [request](https://pypi.org/project/requests/) for fetching data over HTTP
- [csv](https://docs.python.org/3/library/csv.html) for  for handling CSV files.

 *Function download_and_decompress_xz*:
   - This function takes two arguments: url (the URL from which the XZ compressed file will be downloaded) and output_file (the name of the file where the decompressed data will be saved).
   - The function uses the requests library to download the data from the specified URL in chunks and writes these chunks to an XZ file.
   - The lzma module is then used to decompress the XZ file and save the original data in the specified output file.

 *URL and Output File Definition*:
   - The URL (url) is set to **RPKI_ARCHIVE_URLS**, which should be replaced with the actual URL from where you want to fetch the XZ compressed data.
   - The output filename (output_filename) is set to "data.csv", indicating that the decompressed data will be saved in a CSV file named "data.csv".

*Downloading and Decompressing*:
   - The download_and_decompress_xz function is called with the specified URL and output filename as arguments. This function downloads the XZ compressed file from the URL, decompresses it, and saves the decompressed data in "data.csv".

 *Reading and Printing CSV Data*:
   - After the XZ file is downloaded and decompressed, the script reads the data from "data.csv" using Python's csv.DictReader to parse the CSV file.
   - Each row of the CSV file is treated as a dictionary, and the script prints each row to the console.

@romain-fontugne  can you assign me this , I mentioned the above solution

**Comment by MAVRICK-1** [comment]
*It can be done by using following modules :* 
-  [lzma](https://docs.python.org/3/library/lzma.html) for **xz** Decompression
- [request](https://pypi.org/project/requests/) for fetching data over HTTP
- [csv](https://docs.python.org/3/library/csv.html) for  for handling CSV files.

 ### Explanation:
1. *Update URLs*: 
- The URLs used to fetch data need to be updated to point to the new locations or formats where the data is available.
2. *Decompress Files*: 
- the requests library to download the data from the specified URL in chunks and writes these chunks to an XZ file.
-The lzma module is then used to decompress the XZ file and save the original data in the specified output file.
@romain-fontugne  can you assign me this , I mentioned the above solution

**Comment by MAVRICK-1** [comment]
The  xz files can be decompressed using  [lzma](https://docs.python.org/3/library/lzma.html) 
After Decompression we can get the output file as  csv 
here's a rough code snippet
here I m taking the url of "https://ftp.ripe.net/rpki/apnic.tal/2023/11/06/output.json.xz"
```python

import lzma
import json
import csv
import requests

# Define the input and output filenames
output_filename = "output12.csv"
url="https://ftp.ripe.net/rpki/apnic.tal/2023/11/06/output.json.xz"

# Function to convert JSON data to CSV and save to a file
def json_to_csv(json_data, filename):
       # Extract the "roas" list from the JSON data
    roas_list = json_data.get("roas", [])

    # Define the CSV header
    fieldnames = ["asn", "prefix", "maxLength", "ta"]

    # Write "roas" list to CSV file
    with open(filename, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for roa in roas_list:
            writer.writerow(roa)
            
# Function to decompress the XZ file and load JSON data
def decompress_and_load_json():
    response = requests.get(url, stream=True)
    response.raise_for_status()
    open('data.json.xz','wb').write(response.content)
    with lzma.open("data.json.xz", 'rb') as f:
        decompressed_data = f.read()
        json_data = json.loads(decompressed_data.decode('utf-8'))
        json_to_csv(json_data, output_filename)
        

# Decompress the XZ file and load JSON data

decompress_and_load_json()
# Convert JSON data to CSV and save to a file


print(f" CSV file is in {output_filename}")
```
### Import Statements:
- lzma: Module for handling XZ compression.
- json: Module for handling JSON data.
- csv: Module for reading and writing CSV files.
- requests: Module for making HTTP requests.

### Variables:
- output_filename: Specifies the name of the output CSV file.
- url: Specifies the URL from which the compressed JSON file (output.json.xz) will be downloaded.

### Functions:

1. *json_to_csv(json_data, filename)*:
   - Takes JSON data and a filename as input.
   - Extracts the "roas" list from the JSON data.
   - Defines the header for the CSV file.
   - Writes the "roas" list to a CSV file with the specified filename.

2. *decompress_and_load_json()*:
   - Downloads the compressed JSON file (output.json.xz) from the specified URL.
   - Writes the downloaded content to a local file (data.json.xz).
   - Decompresses the data.json.xz file and loads the JSON data.
   - Calls the json_to_csv function to convert the JSON data to CSV and save it to the specified output file.

### Main Execution:
- The program calls the decompress_and_load_json function to perform the decompression and conversion of the JSON data to CSV.
- After execution, the program prints the path to the generated CSV file.


@romain-fontugne  here's a possible solution can you assign me this

**Comment by romain-fontugne** [comment]
Sorry I meant xz format. @MAVRICK-1 go ahead!
